replicaCount: 1

agent:
  logLevel: 1
  clusterID: Kubernetes

  trustDomain: cluster.local

  servingAddress: 0.0.0.0
  servingPort: 6443

  certificateDuration: 120s
  rootCAConfigMapName: istio-ca-root-cert

certificate:
  namespace: istio-system
  group: cert-manager.io
  kind: ClusterIssuer
  name: ca-issuer
  maxDuration: 5m
  preserveCertificateRequests: true

resources: {}
